"""followers

Revision ID: 591e2be0a93c
Revises: 365c147aef29
Create Date: 2021-01-09 17:39:57.085427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591e2be0a93c'
down_revision = '365c147aef29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
